$background = rgb(010101)
$foreground = rgb(F3F2F1)
$color0 = rgb(010101)
$color1 = rgb(24374A)
$color2 = rgb(5B3235)
$color3 = rgb(586C78)
$color4 = rgb(AF468E)
$color5 = rgb(62A7AC)
$color6 = rgb(A6A4A1)
$color7 = rgb(E6E4E3)
$color8 = rgb(A1A09F)
$color9 = rgb(304963)
$color10 = rgb(794346)
$color11 = rgb(7590A0)
$color12 = rgb(E95DBD)
$color13 = rgb(83DFE5)
$color14 = rgb(DEDAD7)
$color15 = rgb(E6E4E3)
