# /* ---- ⚡ https://github.com/EnderSpy29 ⚡ ---- */  #
# This is where you put your own keybinds. Be Mindful to check as well ~/.config/hypr/configs/Keybinds.conf to avoid conflict
# See https://wiki.hyprland.org/Configuring/Keywords/ for Documentation

$mainMod = SUPER
$files = thunar
$term = kitty
$wallpaper = "{wallpaper}"
$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts

# Hyprpaper
$w1 = hyprctl hyprpaper wallpaper "DP-1,~/Pictures/wallpapers/Hyprpaper/Lowpoly_Street.png" && hyprctl hyprpaper wallpaper "DP-2,~/Pictures/wallpapers/Hyprpaper/Tokyo_Pink.png" && wal -n -i "~/Pictures/wallpapers/Hyprpaper/Lowpoly_Street.png"
$w2 = hyprctl hyprpaper wallpaper "DP-1,~/Pictures/wallpapers/Hyprpaper/Fantasy-Lake2.png" && hyprctl hyprpaper wallpaper "DP-2,~/Pictures/wallpapers/Hyprpaper/Fantasy-Landscape2.png" && wal -n -i "~/Pictures/wallpapers/Hyprpaper/Fantasy-Lake2.png"
$w3 = hyprctl hyprpaper wallpaper "DP-1,~/Pictures/wallpapers/Hyprpaper/sushi_keycap.png" && hyprctl hyprpaper wallpaper "DP-2,~/Pictures/wallpapers/Hyprpaper/4k-keyboard.jpg" && wal -n -i "~/Pictures/wallpapers/Hyprpaper/sushi_keycap.png"
$w4 = hyprctl hyprpaper wallpaper "DP-1,~/Pictures/wallpapers/Hyprpaper/Buildings.png" && hyprctl hyprpaper wallpaper "DP-2,~/Pictures/wallpapers/Hyprpaper/nord-chainsaw.png" && wal -n -i "~/Pictures/wallpapers/Hyprpaper/Buildings.png"
$w5 = hyprctl hyprpaper wallpaper "DP-1,~/Pictures/wallpapers/Hyprpaper/MakimaRedRight.png" && hyprctl hyprpaper wallpaper "DP-2,~/Pictures/wallpapers/Hyprpaper/MakimaRedLeft.png" && wal -n -i "~/Pictures/wallpapers/Hyprpaper/MakimaRedRight.png"
$w6 = hyprctl hyprpaper wallpaper "DP-1,~/Pictures/wallpapers/Hyprpaper/MakimaDarkRight.jpg" && hyprctl hyprpaper wallpaper "DP-2,~/Pictures/wallpapers/Hyprpaper/MakimaDarkLeft.jpg" && wal -n -i "~/Pictures/wallpapers/Hyprpaper/MakimaDarkRight.jpg"

bind = CTRL, 1, exec, $w1
bind = CTRL, 1, exec, $UserScripts/wal1.sh
bind = CTRL, 2, exec, $w2
bind = CTRL, 2, exec, $UserScripts/wal2.sh
bind = CTRL, 3, exec, $w3
bind = CTRL, 3, exec, $UserScripts/wal3.sh
bind = CTRL, 4, exec, $w4
bind = CTRL, 4, exec, $UserScripts/wal4.sh
bind = CTRL, 5, exec, $w5
bind = CTRL, 5, exec, $UserScripts/wal5.sh
bind = CTRL, 6, exec, $w6
bind = CTRL, 6, exec, $UserScripts/wal6.sh

# rofi App launcher
bind = $mainMod, N, exec, pkill rofi || rofi-wifi-menu.sh
bindr = $mainMod, $mainMod_L, exec, pkill rofi || rofi -show drun -modi drun,filebrowser,run,window # Super Key to Launch rofi menu
#bind = $mainMod, D, exec, pkill rofi || rofi -show drun -modi drun,filebrowser,run,window

# ags overview
bind = $mainMod, A, exec, pkill rofi || true && ags -t 'overview'

bind = $mainMod, Return, exec, $term  # Launch terminal
bind = $mainMod, Shift_R, exec, $files # Launch file manager

bind = $mainMod ALT, C, exec, $UserScripts/RofiCalc.sh # calculator (qalculate)

# pyprland
bind = $mainMod SHIFT, Return, exec, pypr toggle term # Dropdown terminal
bind = $mainMod, Z, exec, pypr zoom # Toggle Zoom

# User Added Keybinds
bind = $mainMod SHIFT, O, exec, $UserScripts/ZshChangeTheme.sh # Change oh-my-zsh theme
bindn = ALT_L, SHIFT_L, exec, $scriptsDir/SwitchKeyboardLayout.sh # Changing the keyboard layout

# For passthrough keyboard into a VM
# bind = $mainMod ALT, P, submap, passthru
#submap = passthru
# to unbind
#bind = $mainMod ALT, P, submap, reset
#submap = reset

