$background = rgb(180D1E)
$foreground = rgb(FEF1FA)
$color0 = rgb(34283C)
$color1 = rgb(482A55)
$color2 = rgb(69417C)
$color3 = rgb(8E5E9E)
$color4 = rgb(B284BB)
$color5 = rgb(D2A8D4)
$color6 = rgb(F4D1EE)
$color7 = rgb(FEF1FA)
$color8 = rgb(564C5C)
$color9 = rgb(482A55)
$color10 = rgb(69417C)
$color11 = rgb(8E5E9E)
$color12 = rgb(B284BB)
$color13 = rgb(D2A8D4)
$color14 = rgb(F4D1EE)
$color15 = rgb(FEF1FA)