preload = ~/Pictures/wallpapers/Hyprpaper/Tokyo_Pink.png
preload = ~/Pictures/wallpapers/Hyprpaper/Lowpoly_Street.png
preload = ~/Pictures/wallpapers/Hyprpaper/Fantasy-Landscape2.png
preload = ~/Pictures/wallpapers/Hyprpaper/Fantasy-Lake2.png
preload = ~/Pictures/wallpapers/Hyprpaper/sushi_keycap.png
preload = ~/Pictures/wallpapers/Hyprpaper/4k-keyboard.jpg
preload = ~/Pictures/wallpapers/Hyprpaper/Buildings.png
preload = ~/Pictures/wallpapers/Hyprpaper/nord-chainsaw.png
preload = ~/Pictures/wallpapers/Hyprpaper/MakimaRedRight.png
preload = ~/Pictures/wallpapers/Hyprpaper/MakimaRedLeft.png
preload = ~/Pictures/wallpapers/Hyprpaper/MakimaDarkRight.jpg
preload = ~/Pictures/wallpapers/Hyprpaper/MakimaDarkLeft.jpg

#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
wallpaper = DP-1,~/Pictures/wallpapers/Hyprpaper/Lowpoly_Street.png
wallpaper = DP-2,~/Pictures/wallpapers/Hyprpaper/Tokyo_Pink.png

#enable splash text rendering over the wallpaper
splash = false

#fully disable ipc
 ipc = on

