$terminal = foot
$fileManager = thunar
$browser = firefox

# Dual Monitor Config
monitorv2 {
  output = DP-1
  mode = 1920x1080@144
  position = 1080x430
  scale = 1
  sdr_max_luminance = 203
  vrr = 0
  cm = auto
  sdrbrightness = 1
  sdrsaturation = 1
  sdr_min_luminance = 0.005
  supports_hdr = 0
  supports_wide_color = 0
}
monitorv2 {
  output = DP-2
  mode = 1920x1080@144
  position = 0x0
  scale = 1
  transform = 1
  vrr = 0
  cm = auto
  sdrbrightness = 1
  sdrsaturation = 1
  sdr_max_luminance = 203
  sdr_min_luminance = 0.005
  supports_hdr = 0
  supports_wide_color = 0
}

