# Steam Notification fix (Steam launches silently on workspace 10)
windowrulev2 = workspace 10 silent, class:steam

# Remove Overlay in screenshots
layerrule=noanim,selection

# Set Certain Workspaces for certain windows
windowrulev2 = workspace 2, class:vesktop
windowrulev2 = workspace 1, class:floorp
windowrulev2 = workspace 2, class:Youtube Music
#windowrulev2 = workspace 4, class:thunar
#windowrulev2 = workspace 3, class:kitty

# Set Certain Monitors For Certain Workspaces
workspace = 10, monitor:0
workspace = 2, monitor:DP-2

# Custom Opacity
windowrulev2 = opacity 0.9 0.9, class:^(kitty)$
windowrulev2 = opacity 0.75 0.8, class:^(VSCodium|codium-url-handler)$
windowrulev2 = opacity 0.9 0.9, class:^(mousepad)$
windowrulev2 = opacity 0.8 0.8, class:^([Dd]iscord|[Vv]esktop)$
windowrulev2 = opacity 0.9 0.9, class:^([Tt]hunar)$


# Float Windows n Stuff
windowrulev2 = float, class:(floating) # ensure you have defined a floating window class
windowrulev2 = float, class:(clipse) # Clipboard
windowrulev2 = float, class:(waypaper)$
windowrulev2 = float, class:(cava)$

# Something else idk
# windowrulev2 = suppressevent maximize, class:.*